version: '3.4'

services:
  expenseapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # 8000 on your machine -> 80 inside container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ExpenseDB;User=sa;Password=Your_password123;TrustServerCertificate=True;
